### PR TITLE
WOMBAT: Limit max temperature in calculations of Schmidt number

### LINKED ISSUE #35: WOMBAT: limit temperature in calculations of Schmidt number
In warm climate simulations, it's possible for the Schmidt numbers calculated in WOMBAT to go negative, causing the model to crash. This is because the [formulation used to calculate the Schmidt number](https://github.com/ACCESS-NRI/MOM5/blob/1c4f09ac8724d75d47e3ab9969ee4c741c83192c/src/mom5/ocean_csiro_bgc/csiro_bgc.F90#L1013-L1026) is only really valid up to 30C or something. It is common to limit the temperature to a valid range when performing this calculation, but this is not done in the version of WOMBAT used in ACCESS-ESM1.5 (on branch: `access-esm1.5`).

This issue was encountered recently and [reported by a user](https://forum.access-hive.org.au/t/wombat-crashing-in-miocene-access-esm1-5-simulation/4344) running simulations of the Miocene with ACCESS-ESM1.5. As a temporary workaround, we've provided a prerelease of ACCESS-ESM1.5 that includes the temperature limiting, but we get this change into an official release. The first step is to merge the change into the `access-esm1.5` branch of `MOM5`.

### PR DESCRIPTION
**Pull request by dougiesquire**
Closes #35

### CODE REVIEW

File: src/mom5/ocean_csiro_bgc/csiro_bgc.F90 [hunk 1]
```diff
@@ -1003,10 +1004,12 @@ subroutine csiro_bgc_sbc(isc, iec, jsc, jec, isd, ied, jsd, jed, &
...
-    sc_co2(i,j) = 2073.1 + t_prog(indtemp)%field(i,j,1,time%taum1) * &
-         (-125.62 + t_prog(indtemp)%field(i,j,1,time%taum1) *        &
-          (3.6276 + t_prog(indtemp)%field(i,j,1,time%taum1) *        &
-           (-0.043219))) * grid%tmask(i,j,1)
+    ! Limit temp used for Schmidt number calculation.
+    schmidt_temp = min(35.0, t_prog(indtemp)%field(i,j,1,time%taum1))
+    sc_co2(i,j) = 2073.1 + schmidt_temp * &
+        (-125.62 + schmidt_temp *         &
+        (3.6276 + schmidt_temp *          &
+        (-0.043219))) * grid%tmask(i,j,1)
```
Comment (aidanheerdegen) [inline src/mom5/ocean_csiro_bgc/csiro_bgc.F90:1012]: I don't expect this to be fixed, but felt duty bound to say "wow there are a lot of magic numbers here".

File: src/mom5/ocean_csiro_bgc/csiro_bgc.F90 [hunk 2]
```diff
@@ -1018,10 +1021,12 @@ subroutine csiro_bgc_sbc(isc, iec, jsc, jec, isd, ied, jsd, jed, &
...
-    sc_o2(i,j) = 1638.0 + t_prog(indtemp)%field(i,j,1,time%taum1) *  &
-         (-81.83 + t_prog(indtemp)%field(i,j,1,time%taum1) *         &
-          (1.483 + t_prog(indtemp)%field(i,j,1,time%taum1) *         &
-           (-0.008004))) * grid%tmask(i,j,1)
+    ! Limit temp used for Schmidt number calculation.
+    schmidt_temp = min(35.0, t_prog(indtemp)%field(i,j,1,time%taum1))
+    sc_o2(i,j) = 1638.0 + schmidt_temp * &
+        (-81.83 + schmidt_temp *         &
+        (1.483 + schmidt_temp *          &
+        (-0.008004))) * grid%tmask(i,j,1)
```
Comment (aidanheerdegen) [inline src/mom5/ocean_csiro_bgc/csiro_bgc.F90:1029]: I don't expect this to be fixed, but felt duty bound to say "wow there are a lot of magic numbers here".

**Review by aidanheerdegen — APPROVED** [review]
Looks good to me.

File: src/mom5/ocean_csiro_bgc/csiro_bgc.F90 (hunk 1 above)
Comment (dougiesquire) [reply src/mom5/ocean_csiro_bgc/csiro_bgc.F90:1012]: Hocus pocus

File: src/mom5/ocean_csiro_bgc/csiro_bgc.F90 (hunk 2 above)
Comment (dougiesquire) [reply src/mom5/ocean_csiro_bgc/csiro_bgc.F90:1029]: Alakazam

**Comment by aidanheerdegen** [comment]
Should this be merged into `master` too?

**Comment by dougiesquire** [comment]
It could. But I hope the next OM2 release will use generic tracer WOMBAT so is there any point?
